#############################################################################
# Makefile for building: PLAY-LynxTracker
# Generated by qmake (2.01a) (Qt 4.5.2) on: mer. juil. 22 09:35:48 2009
# Project:  PLAY-LynxTracker.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile PLAY-LynxTracker.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = LynxTracker.cpp \
		main.cpp \
		TrackView.cpp \
		NoteEntry.cpp moc_LynxTracker.cpp
OBJECTS       = LynxTracker.o \
		main.o \
		TrackView.o \
		NoteEntry.o \
		moc_LynxTracker.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		PLAY-LynxTracker.pro
QMAKE_TARGET  = PLAY-LynxTracker
DESTDIR       = 
TARGET        = PLAY-LynxTracker

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_LynxTracker.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: PLAY-LynxTracker.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile PLAY-LynxTracker.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile PLAY-LynxTracker.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/PLAY-LynxTracker1.0.0 || $(MKDIR) .tmp/PLAY-LynxTracker1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/PLAY-LynxTracker1.0.0/ && $(COPY_FILE) --parents LynxTracker.h TrackView.h NoteEntry.h .tmp/PLAY-LynxTracker1.0.0/ && $(COPY_FILE) --parents LynxTracker.cpp main.cpp TrackView.cpp NoteEntry.cpp .tmp/PLAY-LynxTracker1.0.0/ && $(COPY_FILE) --parents LynxTracker.ui .tmp/PLAY-LynxTracker1.0.0/ && (cd `dirname .tmp/PLAY-LynxTracker1.0.0` && $(TAR) PLAY-LynxTracker1.0.0.tar PLAY-LynxTracker1.0.0 && $(COMPRESS) PLAY-LynxTracker1.0.0.tar) && $(MOVE) `dirname .tmp/PLAY-LynxTracker1.0.0`/PLAY-LynxTracker1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/PLAY-LynxTracker1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_LynxTracker.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_LynxTracker.cpp
moc_LynxTracker.cpp: ui_LynxTracker.h \
		TrackView.h \
		NoteEntry.h \
		LynxTracker.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) LynxTracker.h -o moc_LynxTracker.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_LynxTracker.h
compiler_uic_clean:
	-$(DEL_FILE) ui_LynxTracker.h
ui_LynxTracker.h: LynxTracker.ui
	/usr/bin/uic-qt4 LynxTracker.ui -o ui_LynxTracker.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

LynxTracker.o: LynxTracker.cpp LynxTracker.h \
		ui_LynxTracker.h \
		TrackView.h \
		NoteEntry.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LynxTracker.o LynxTracker.cpp

main.o: main.cpp LynxTracker.h \
		ui_LynxTracker.h \
		TrackView.h \
		NoteEntry.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

TrackView.o: TrackView.cpp TrackView.h \
		NoteEntry.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TrackView.o TrackView.cpp

NoteEntry.o: NoteEntry.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NoteEntry.o NoteEntry.cpp

moc_LynxTracker.o: moc_LynxTracker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_LynxTracker.o moc_LynxTracker.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

