######################################################################
# Automatically generated by qmake (2.01a) sam. juil. 11 23:09:24 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += LynxTracker.h TrackView.h NoteEntry.h
FORMS += LynxTracker.ui
SOURCES += LynxTracker.cpp main.cpp TrackView.cpp NoteEntry.cpp
